### ISSUE TITLE
Micro freeze when pressing shift

### ISSUE THREAD

**Issue by Dabeuliou** [parnic/breakables#1]
Hello,

I have micro freezes when i press shift.
I know it's Breakables because it happens when it's the only one addon i deactivate.
I've tried to comment the Breakables:OnMouseDown function, but it keeps doing the same.

Thanks anyway for the addon!

**Comment by parnic** [comment]
I have no idea what to say about that. If you've removed the only part of the code that actually does anything in response to Shift but you still see a problem when pressing Shift, then...it sounds like Breakables is not going to work for you.

**Comment by Dabeuliou** [comment]
Well, I think it's related to the addon because:
- with all the addons except Breakables: no freeze with shift
- with no addon at all: no freeze with shift
- with only Breakables: freeze with shift

It may be due to the embedded Ace3 libs, but i'm no expert in lua.

I've been using the addon for years without any problem. I'm just back from a six months break and have updated to the last version.

**Comment by parnic** [comment]
Yeah, I'm not saying it isn't happening, I just don't know what to do about it
