### ISSUE TITLE
Incorrect milling outcome

### ISSUE THREAD

**Issue by ThaDanus** [parnic/breakables#11]
Hi, playing Cataclysm classic here.
Love the addon, but some herbs have an incorrect milling outcome:

Khadgar's Whisker and Goldthorn are listed as resulting in Dusky Pigment / Verdant Pigment
--> Should be Emerald Pigment / Indigo Pigment as listed on the item details of Emerald Pigment.

![image](https://github.com/user-attachments/assets/39194971-d549-4ee9-8187-7b59b2b1c025)
![image](https://github.com/user-attachments/assets/a8afbcb0-e2c8-4e8e-9ce4-51dd68971643)

![image](https://github.com/user-attachments/assets/4c93d59b-f942-4280-a698-42d3c105e050)

**Comment by parnic** [comment]
I'm not sure which addon is providing that that outcome information, but it isn't Breakables. :)

**Comment by ThaDanus** [comment]
My bad...too many addons, this comes from Profession Assistance instead.
Apologies :)
