### ISSUE TITLE
Enchanter bar not populating with BoE greens in bag

### ISSUE THREAD

**Issue by red13dotnet** [parnic/breakables#2]
Hello Parnic, need to report a bug with handling for disenchanting.

But first, thank you.  This addon has made aspects of playing much more enjoyable.

I also tried posting this in the curseforge comments but they seem to be having another problem with their comment system. I will likely try again later since all indications show that as your preferred method for reports.

---Report
I am using version 1.8.5-Wrath

Things work great for my scribe and jewelcrafter but the bar will not appear for my enchanter, even with a bag full of BoE greens.

I have tried all available options in the menu with no change. 

If I force the bar to appear, the DE button appears but none of the items. 

I have also attempted disabling all other addons and reloading, with no change.

Let me know if you need any further information from me.

**Comment by parnic** [comment]
I prefer GitHub, but nobody ever uses it.

Do you have the enchanting skill level appropriate for the bag full of greens? Honestly I haven't been able to test that part properly (skill level required) so there may just be a bug.

**Comment by red13dotnet** [comment]
Yes, i am able to D/E the same greens manually.

**Comment by parnic** [comment]
Please try the 1.8.6 alpha1 build that's pushing now or locally apply commit https://github.com/parnic/breakables/commit/80e495f707cf020355357dc3f3669e3370471a4b and let me know if it works!

**Comment by red13dotnet** [comment]
Limited testing done so far but it does appear to work.
Ill farm for another bag of greens and comment again if I see anything strange.
Thank you!
