### ISSUE TITLE
Dragonflight Disenchanting Items Suggestion

### ISSUE THREAD

**Issue by Ovaldo** [parnic/breakables#4]
I would appreciate if the Insight of the Blue enchanting specialization items would be added to the addon.

Items like
Seal of Order https://www.wowhead.com/item=200941/seal-of-order#comments
Vibrant Emulsion https://www.wowhead.com/item=200942/vibrant-emulsion
Whispering Band https://www.wowhead.com/item=200943/whispering-band

and several others.

Thank you, I appreciate the work you've done on this addon!

**Comment by parnic** [comment]
Thanks for creating the issue, I haven't gotten around to playing my Enchanter on Dragonflight yet.

Do all of the items in question have that "Mystic" tag on them? I'm wondering if I'd need to make an explicit list of item IDs or if I can detect them programmatically.

**Comment by parnic** [comment]
Does this list look complete? https://www.wowhead.com/items/miscellaneous/other?filter=166;10;0#name=mystic
