### ISSUE TITLE
Wrath Classic, breakables button dissapears after update to 1.9.8 - wrath

### ISSUE THREAD

**Issue by Blitzed** [parnic/breakables#5]
there is no error log that i can link you, no errors at all. I get a disenchantable item it shows briefly to the having the buttons dissapearing.

I have tried deleting the addon and let it reinstall but to no avail.

**Comment by parnic** [comment]
I'll take a look.

**Comment by Blitzed** [comment]
> I'll take a look.

Thanks a lot :)

**Comment by parnic** [comment]
I'm logged into Wrath Classic with a character that has Enchanting a single green item in her bags. The button shows up and is clickable for me, it doesn't disappear. Is there any other relevant info that would help me reproduce the problem on my end?

edit: have you tried some of the settings like "Show soulbound items" to see if that changes anything?

**Comment by parnic** [comment]
If you want to attach your SavedVariables\Breakables.lua file here, that might help.

**Comment by Blitzed** [comment]
I tried as well on my scribe, didn't show up either, i can't other than supply you with the breakables.lua as there is no errors i also found it odd as it worked with the previous version. Thanks for taking the time to see it through tho <3

The enchanter Is a warrior
Scribe is Deathknight
Both Humans

[Breakables.zip](https://github.com/parnic/breakables/files/10190535/Breakables.zip)

**Comment by parnic** [comment]
Yeah, share that file, if you would, and let me know what professions you have on the character showing the problem as well as what class the character is (if you're a Rogue with Pick Lock, specifically).

**Comment by Blitzed** [comment]
I updated the original message since I tried uploading .lua and .rar but it wasn't supported :)

**Comment by parnic** [comment]
Thanks! Any other professions on those characters?

**Comment by Blitzed** [comment]
On these its
Engineering / Enchanting
Engineering / Inscription

Thats it :)

**Comment by Blitzed** [comment]
tested some more, the thing still persist.. i log into my warrior "enchanting/engi" had some greens in my bag, Breakables is showing, disenchant 1 item and then it dissapear. Again there is no error msg or anything, also tried with all other addons disabled but nothing.

**Comment by Blitzed** [comment]
Ended up with downloading v 1.9.7-wrath and here all is good :)

**Comment by parnic** [comment]
This should be fixed in v1.9.9.

**Comment by Blitzed** [comment]
> This should be fixed in v1.9.9.

Confirmed, all is good <3 thanks for your time!!
