### ISSUE TITLE
Request to add items as breakable for Enchanters

### ISSUE THREAD

**Issue by Mithmacil** [parnic/breakables#6]
Not sure if this is possible as an Enchanter there are 8 items that can be DE'd  that dont show.
Can these be added? I do have show Soulbound items on.
Seal of Order - Item# 200941
Everflowing Inkwell - Item# 200940
Chromatic Pocketwatch - Item# 200939
Carving of Awakening - Item# 200947
Vibrant Emulsion - Item# 200942
Whispering Band - Item# 200943
Valiant Hammer - Item# 200945
Thunderous Blade - Item# 200946

**Comment by parnic** [comment]
I tried to add these in #4 but I guess it didn't take. Will try to fix.

**Comment by parnic** [comment]
Should be fixed for real in v1.9.10
