### ISSUE TITLE
WotLK Classic herb Goldclover not recognized as millable

### ISSUE THREAD

**Issue by b-morgan** [parnic/breakables#8]
With Breakables 1.9.17 on WotLK Classic 3.4.2, Goldclover (36901) is not recognized as millable but Tiger Lily (36904) is recognized. The second line of both tooltips is "Millable" (ITEM_MILLABLE).

Let me know if I need to capture or provide any additional information.

**Comment by b-morgan** [comment]
I just verified that this fails with all addons disabled except Breakables.

**Comment by b-morgan** [comment]
NVM, Goldclover had somehow found its way into the ignore list.

**Comment by parnic** [comment]
I should probably create a confirm pop-up for ignoring things. It's a little too easy to do right now.

**Comment by b-morgan** [comment]
I cleared the list but now I'm not sure how to put something on the list if I wanted to, lol.

**Comment by parnic** [comment]
Right click the box you'd normally left click to break it.

**Comment by b-morgan** [comment]
Neither the readme.md nor the CurseForge addon description mentions that...😉

**Comment by parnic** [comment]
Good point.
